### ISSUE TITLE
Not really an issue but...

### ISSUE THREAD

**Issue by vinhtvu2** [quantity-digital/acf-read-only#1]
The version number is not updated in the acf-read-only.php file, so Github Updater plugin doesn't update to the latest version.

Not an issue, just figure I'd point it out.

**Comment by NicolajKN** [comment]
Hi, 

I changed the version number in the plugin comment. Does it work now?

**Comment by vinhtvu2** [comment]
That has got to be the fastest response I've ever seen! I installed in DEV and saw 0.3.0, went to install in QA and it was already 0.4.0, I was like... maybe I'm seeing things this early...

Everything worked. Thanks!

**Comment by NicolajKN** [comment]
Cool man! Had no idea anyone was using this plugin actually, so great to get feedback.

Have a great day!
